

insert into Tags values (1,"7");
insert into Tags values (2,"007 (series)");
insert into Tags values (3,"18th century");
insert into Tags values (4,"1920s");
insert into Tags values (5,"1930s");
insert into Tags values (6,"1950s");
insert into Tags values (7,"1960s");
insert into Tags values (8,"1970s");
insert into Tags values (9,"1980s");
insert into Tags values (10,"19th century");
insert into Tags values (11,"3d");
insert into Tags values (12,"70mm");
insert into Tags values (13,"80s");
insert into Tags values (14,"11-Sep");
insert into Tags values (15,"aardman");
insert into Tags values (16,"aardman studios");
insert into Tags values (17,"abortion");
insert into Tags values (18,"absurd");
insert into Tags values (19,"action");
insert into Tags values (20,"action packed");
insert into Tags values (21,"adaptation");
insert into Tags values (22,"adapted from:book");
insert into Tags values (23,"adapted from:comic");
insert into Tags values (24,"adapted from:game");
insert into Tags values (25,"addiction");
insert into Tags values (26,"adolescence");
insert into Tags values (27,"adoption");
insert into Tags values (28,"adultery");
insert into Tags values (29,"adventure");
insert into Tags values (30,"affectionate");
insert into Tags values (31,"afi 100");
insert into Tags values (32,"afi 100 (laughs)");
insert into Tags values (33,"afi 100 (movie quotes)");
insert into Tags values (34,"africa");
insert into Tags values (35,"afterlife");
insert into Tags values (36,"aging");
insert into Tags values (37,"aids");
insert into Tags values (38,"airplane");
insert into Tags values (39,"airport");
insert into Tags values (40,"alaska");
insert into Tags values (41,"alcatraz");
insert into Tags values (42,"alcoholism");
insert into Tags values (43,"alien");
insert into Tags values (44,"alien invasion");
insert into Tags values (45,"aliens");
insert into Tags values (46,"allegory");
insert into Tags values (47,"almodovar");
insert into Tags values (48,"alone in the world");
insert into Tags values (49,"alter ego");
insert into Tags values (50,"alternate endings");
insert into Tags values (51,"alternate history");
insert into Tags values (52,"alternate reality");
insert into Tags values (53,"alternate universe");
insert into Tags values (54,"amazing cinematography");
insert into Tags values (55,"amazing photography");
insert into Tags values (56,"american civil war");
insert into Tags values (57,"amnesia");
insert into Tags values (58,"amy smart");
insert into Tags values (59,"android(s)/cyborg(s)");
insert into Tags values (60,"androids");
insert into Tags values (61,"animal movie");
insert into Tags values (62,"animals");
insert into Tags values (63,"animated");
insert into Tags values (64,"animation");
insert into Tags values (65,"anime");
insert into Tags values (66,"antarctica");
insert into Tags values (67,"anti-hero");
insert into Tags values (68,"anti-semitism");
insert into Tags values (69,"anti-war");
insert into Tags values (70,"apocalypse");
insert into Tags values (71,"archaeology");
insert into Tags values (72,"argentina");
insert into Tags values (73,"arms dealer");
insert into Tags values (74,"arnold");
insert into Tags values (75,"art");
insert into Tags values (76,"art house");
insert into Tags values (77,"artificial intelligence");
insert into Tags values (78,"artist");
insert into Tags values (79,"artistic");
insert into Tags values (80,"artsy");
insert into Tags values (81,"assassin");
insert into Tags values (82,"assassination");
insert into Tags values (83,"assassins");
insert into Tags values (84,"astronauts");
insert into Tags values (85,"atheism");
insert into Tags values (86,"atmospheric");
insert into Tags values (87,"australia");
insert into Tags values (88,"australian");
insert into Tags values (89,"author:alan moore");
insert into Tags values (90,"author:neil gaiman");
insert into Tags values (91,"autism");
insert into Tags values (92,"aviation");
insert into Tags values (93,"awesome");
insert into Tags values (94,"awesome soundtrack");
insert into Tags values (95,"awful");
insert into Tags values (96,"bad");
insert into Tags values (97,"bad acting");
insert into Tags values (98,"bad cgi");
insert into Tags values (99,"bad ending");
insert into Tags values (100,"bad plot");
insert into Tags values (101,"bad science");
insert into Tags values (102,"bad script");
insert into Tags values (103,"bad sequel");
insert into Tags values (104,"ballet");
insert into Tags values (105,"bank robbery");
insert into Tags values (106,"baseball");
insert into Tags values (107,"based on a book");
insert into Tags values (108,"based on a comic");
insert into Tags values (109,"based on a play");
insert into Tags values (110,"based on a true story");
insert into Tags values (111,"based on a tv show");
insert into Tags values (112,"based on a video game");
insert into Tags values (113,"based on book");
insert into Tags values (114,"based on comic");
insert into Tags values (115,"based on true story");
insert into Tags values (116,"basketball");
insert into Tags values (117,"batman");
insert into Tags values (118,"bdsm");
insert into Tags values (119,"beatles");
insert into Tags values (120,"beautiful");
insert into Tags values (121,"beautiful scenery");
insert into Tags values (122,"beautifully filmed");
insert into Tags values (123,"beauty pageant");
insert into Tags values (124,"beer");
insert into Tags values (125,"berlin");
insert into Tags values (126,"best of 2005");
insert into Tags values (127,"best war films");
insert into Tags values (128,"betrayal");
insert into Tags values (129,"better than expected");
insert into Tags values (130,"better than the american version");
insert into Tags values (131,"biblical");
insert into Tags values (132,"big budget");
insert into Tags values (133,"biographical");
insert into Tags values (134,"biography");
insert into Tags values (135,"biopic");
insert into Tags values (136,"birds");
insert into Tags values (137,"biting");
insert into Tags values (138,"bittersweet");
insert into Tags values (139,"bizarre");
insert into Tags values (140,"black and white");
insert into Tags values (141,"black comedy");
insert into Tags values (142,"blaxploitation");
insert into Tags values (143,"bleak");
insert into Tags values (144,"blindness");
insert into Tags values (145,"blood");
insert into Tags values (146,"bloody");
insert into Tags values (147,"boarding school");
insert into Tags values (148,"boat");
insert into Tags values (149,"bollywood");
insert into Tags values (150,"bombs");
insert into Tags values (151,"bond");
insert into Tags values (152,"book");
insert into Tags values (153,"book was better");
insert into Tags values (154,"books");
insert into Tags values (155,"boring");
insert into Tags values (156,"boring!");
insert into Tags values (157,"boston");
insert into Tags values (158,"bowling");
insert into Tags values (159,"boxing");
insert into Tags values (160,"brainwashing");
insert into Tags values (161,"brazil");
insert into Tags values (162,"breathtaking");
insert into Tags values (163,"brilliant");
insert into Tags values (164,"british");
insert into Tags values (165,"british comedy");
insert into Tags values (166,"broadway");
insert into Tags values (167,"brothers");
insert into Tags values (168,"brutal");
insert into Tags values (169,"brutality");
insert into Tags values (170,"buddy movie");
insert into Tags values (171,"bullshit history");
insert into Tags values (172,"bullying");
insert into Tags values (173,"business");
insert into Tags values (174,"c.s. lewis");
insert into Tags values (175,"california");
insert into Tags values (176,"camp");
insert into Tags values (177,"campy");
insert into Tags values (178,"canada");
insert into Tags values (179,"cancer");
insert into Tags values (180,"cannibalism");
insert into Tags values (181,"caper");
insert into Tags values (182,"capitalism");
insert into Tags values (183,"car chase");
insert into Tags values (184,"carrie-anne moss");
insert into Tags values (185,"cars");
insert into Tags values (186,"cartoon");
insert into Tags values (187,"casino");
insert into Tags values (188,"catastrophe");
insert into Tags values (189,"cathartic");
insert into Tags values (190,"catholicism");
insert into Tags values (191,"censorship");
insert into Tags values (192,"cerebral");
insert into Tags values (193,"cgi");
insert into Tags values (194,"character study");
insert into Tags values (195,"chase");
insert into Tags values (196,"cheating");
insert into Tags values (197,"cheerleading");
insert into Tags values (198,"cheesy");
insert into Tags values (199,"chess");
insert into Tags values (200,"chicago");
insert into Tags values (201,"chick flick");
insert into Tags values (202,"child abuse");
insert into Tags values (203,"childhood");
insert into Tags values (204,"children");
insert into Tags values (205,"china");
insert into Tags values (206,"chocolate");
insert into Tags values (207,"chris tucker");
insert into Tags values (208,"christian");
insert into Tags values (209,"christianity");
insert into Tags values (210,"christmas");
insert into Tags values (211,"cia");
insert into Tags values (212,"cinematography");
insert into Tags values (213,"circus");
insert into Tags values (214,"civil war");
insert into Tags values (215,"classic");
insert into Tags values (216,"classic car");
insert into Tags values (217,"classical music");
insert into Tags values (218,"claustrophobic");
insert into Tags values (219,"claymation");
insert into Tags values (220,"clever");
insert into Tags values (221,"clones");
insert into Tags values (222,"cloning");
insert into Tags values (223,"clowns");
insert into Tags values (224,"coen bros");
insert into Tags values (225,"coen brothers");
insert into Tags values (226,"cold war");
insert into Tags values (227,"college");
insert into Tags values (228,"colonialism");
insert into Tags values (229,"colourful");
insert into Tags values (230,"comedy");
insert into Tags values (231,"comic");
insert into Tags values (232,"comic book");
insert into Tags values (233,"comic book adaption");
insert into Tags values (234,"comics");
insert into Tags values (235,"coming of age");
insert into Tags values (236,"coming-of-age");
insert into Tags values (237,"communism");
insert into Tags values (238,"compassionate");
insert into Tags values (239,"competition");
insert into Tags values (240,"complex");
insert into Tags values (241,"complex characters");
insert into Tags values (242,"complicated");
insert into Tags values (243,"complicated plot");
insert into Tags values (244,"computer animation");
insert into Tags values (245,"computer game");
insert into Tags values (246,"computers");
insert into Tags values (247,"con artists");
insert into Tags values (248,"con men");
insert into Tags values (249,"confrontational");
insert into Tags values (250,"confusing");
insert into Tags values (251,"conspiracy");
insert into Tags values (252,"conspiracy theory");
insert into Tags values (253,"controversial");
insert into Tags values (254,"cooking");
insert into Tags values (255,"cool");
insert into Tags values (256,"corny");
insert into Tags values (257,"corporate america");
insert into Tags values (258,"corruption");
insert into Tags values (259,"costume drama");
insert into Tags values (260,"courage");
insert into Tags values (261,"court");
insert into Tags values (262,"courtroom");
insert into Tags values (263,"courtroom drama");
insert into Tags values (264,"crappy sequel");
insert into Tags values (265,"crazy");
insert into Tags values (266,"creativity");
insert into Tags values (267,"creepy");
insert into Tags values (268,"crime");
insert into Tags values (269,"crime gone awry");
insert into Tags values (270,"criterion");
insert into Tags values (271,"cross dressing");
insert into Tags values (272,"crude humor");
insert into Tags values (273,"cuba");
insert into Tags values (274,"cult");
insert into Tags values (275,"cult classic");
insert into Tags values (276,"cult film");
insert into Tags values (277,"culture clash");
insert into Tags values (278,"cute");
insert into Tags values (279,"cute!");
insert into Tags values (280,"cyberpunk");
insert into Tags values (281,"cyborgs");
insert into Tags values (282,"cynical");
insert into Tags values (283,"dance");
insert into Tags values (284,"dancing");
insert into Tags values (285,"dark");
insert into Tags values (286,"dark comedy");
insert into Tags values (287,"dark fantasy");
insert into Tags values (288,"dark hero");
insert into Tags values (289,"dark humor");
insert into Tags values (290,"dc comics");
insert into Tags values (291,"deadpan");
insert into Tags values (292,"death");
insert into Tags values (293,"death penalty");
insert into Tags values (294,"demons");
insert into Tags values (295,"depp & burton");
insert into Tags values (296,"depressing");
insert into Tags values (297,"depression");
insert into Tags values (298,"desert");
insert into Tags values (299,"destiny");
insert into Tags values (300,"detective");
insert into Tags values (301,"devil");
insert into Tags values (302,"dialogue");
insert into Tags values (303,"dialogue driven");
insert into Tags values (304,"dinosaurs");
insert into Tags values (305,"directorial debut");
insert into Tags values (306,"disability");
insert into Tags values (307,"disappointing");
insert into Tags values (308,"disaster");
insert into Tags values (309,"disney");
insert into Tags values (310,"disney animated feature");
insert into Tags values (311,"distopia");
insert into Tags values (312,"disturbing");
insert into Tags values (313,"divorce");
insert into Tags values (314,"doctors");
insert into Tags values (315,"documentary");
insert into Tags values (316,"dog");
insert into Tags values (317,"dogs");
insert into Tags values (318,"dolphins");
insert into Tags values (319,"downbeat");
insert into Tags values (320,"dr. seuss");
insert into Tags values (321,"dragon");
insert into Tags values (322,"dragons");
insert into Tags values (323,"drama");
insert into Tags values (324,"dramatic");
insert into Tags values (325,"dreamlike");
insert into Tags values (326,"dreams");
insert into Tags values (327,"dreamworks");
insert into Tags values (328,"drinking");
insert into Tags values (329,"drug abuse");
insert into Tags values (330,"drug addiction");
insert into Tags values (331,"drugs");
insert into Tags values (332,"dumb");
insert into Tags values (333,"dumb but funny");
insert into Tags values (334,"dynamic cgi action");
insert into Tags values (335,"dysfunctional family");
insert into Tags values (336,"dystopia");
insert into Tags values (337,"dystopic future");
insert into Tags values (338,"earnest");
insert into Tags values (339,"easily confused with other movie(s) (title)");
insert into Tags values (340,"east germany");
insert into Tags values (341,"eccentricity");
insert into Tags values (342,"ecology");
insert into Tags values (343,"educational");
insert into Tags values (344,"eerie");
insert into Tags values (345,"effects");
insert into Tags values (346,"egypt");
insert into Tags values (347,"emma watson");
insert into Tags values (348,"emotional");
insert into Tags values (349,"end of the world");
insert into Tags values (350,"england");
insert into Tags values (351,"enigmatic");
insert into Tags values (352,"ennio morricone");
insert into Tags values (353,"enormously long battle scene");
insert into Tags values (354,"ensemble cast");
insert into Tags values (355,"entertaining");
insert into Tags values (356,"entirely dialogue");
insert into Tags values (357,"environment");
insert into Tags values (358,"environmental");
insert into Tags values (359,"epic");
insert into Tags values (360,"erotic");
insert into Tags values (361,"espionage");
insert into Tags values (362,"ethnic conflict");
insert into Tags values (363,"evolution");
insert into Tags values (364,"excellent");
insert into Tags values (365,"excellent script");
insert into Tags values (366,"exceptional acting");
insert into Tags values (367,"exciting");
insert into Tags values (368,"existentialism");
insert into Tags values (369,"explosions");
insert into Tags values (370,"factual");
insert into Tags values (371,"fairy tale");
insert into Tags values (372,"fairy tales");
insert into Tags values (373,"fake documentary");
insert into Tags values (374,"family");
insert into Tags values (375,"family bonds");
insert into Tags values (376,"family drama");
insert into Tags values (377,"fantasy");
insert into Tags values (378,"fantasy world");
insert into Tags values (379,"farce");
insert into Tags values (380,"fascism");
insert into Tags values (381,"fashion");
insert into Tags values (382,"fast paced");
insert into Tags values (383,"father daughter relationship");
insert into Tags values (384,"father son relationship");
insert into Tags values (385,"father-son relationship");
insert into Tags values (386,"fbi");
insert into Tags values (387,"feel good movie");
insert into Tags values (388,"feel-good");
insert into Tags values (389,"fight scenes");
insert into Tags values (390,"fighting");
insert into Tags values (391,"fighting the system");
insert into Tags values (392,"figure skating");
insert into Tags values (393,"film noir");
insert into Tags values (394,"finnish");
insert into Tags values (395,"firefly");
insert into Tags values (396,"first contact");
insert into Tags values (397,"fish");
insert into Tags values (398,"flashbacks");
insert into Tags values (399,"food");
insert into Tags values (400,"football");
insert into Tags values (401,"forceful");
insert into Tags values (402,"foreign");
insert into Tags values (403,"foul language");
insert into Tags values (404,"fountain of youth");
insert into Tags values (405,"france");
insert into Tags values (406,"franchise");
insert into Tags values (407,"francis ford copolla");
insert into Tags values (408,"free speech");
insert into Tags values (409,"free to download");
insert into Tags values (410,"freedom");
insert into Tags values (411,"french");
insert into Tags values (412,"friendship");
insert into Tags values (413,"frightening");
insert into Tags values (414,"fun");
insert into Tags values (415,"fun movie");
insert into Tags values (416,"funniest movies");
insert into Tags values (417,"funny");
insert into Tags values (418,"funny as hell");
insert into Tags values (419,"future");
insert into Tags values (420,"futuristic");
insert into Tags values (421,"gambling");
insert into Tags values (422,"gangs");
insert into Tags values (423,"gangster");
insert into Tags values (424,"gangsters");
insert into Tags values (425,"gay");
insert into Tags values (426,"gay character");
insert into Tags values (427,"geek");
insert into Tags values (428,"geeks");
insert into Tags values (429,"genetics");
insert into Tags values (430,"genius");
insert into Tags values (431,"genocide");
insert into Tags values (432,"george orwell");
insert into Tags values (433,"german");
insert into Tags values (434,"germany");
insert into Tags values (435,"ghosts");
insert into Tags values (436,"ghosts/afterlife");
insert into Tags values (437,"giant robots");
insert into Tags values (438,"gilliam");
insert into Tags values (439,"girlie movie");
insert into Tags values (440,"glbt");
insert into Tags values (441,"global warming");
insert into Tags values (442,"god");
insert into Tags values (443,"golden palm");
insert into Tags values (444,"golf");
insert into Tags values (445,"good");
insert into Tags values (446,"good acting");
insert into Tags values (447,"good action");
insert into Tags values (448,"good dialogue");
insert into Tags values (449,"good music");
insert into Tags values (450,"good romantic comedies");
insert into Tags values (451,"good sequel");
insert into Tags values (452,"good soundtrack");
insert into Tags values (453,"good story");
insert into Tags values (454,"good versus evil");
insert into Tags values (455,"goofy");
insert into Tags values (456,"gore");
insert into Tags values (457,"goretastic");
insert into Tags values (458,"gory");
insert into Tags values (459,"goth");
insert into Tags values (460,"gothic");
insert into Tags values (461,"graphic design");
insert into Tags values (462,"graphic novel");
insert into Tags values (463,"gratuitous violence");
insert into Tags values (464,"great");
insert into Tags values (465,"great acting");
insert into Tags values (466,"great cinematography");
insert into Tags values (467,"great dialogue");
insert into Tags values (468,"great ending");
insert into Tags values (469,"great movie");
insert into Tags values (470,"great music");
insert into Tags values (471,"great soundtrack");
insert into Tags values (472,"greed");
insert into Tags values (473,"grim");
insert into Tags values (474,"grindhouse");
insert into Tags values (475,"gritty");
insert into Tags values (476,"gross-out");
insert into Tags values (477,"gruesome");
insert into Tags values (478,"guilt");
insert into Tags values (479,"guilty pleasure");
insert into Tags values (480,"gulf war");
insert into Tags values (481,"gunfight");
insert into Tags values (482,"guns");
insert into Tags values (483,"gypsy accent");
insert into Tags values (484,"hackers");
insert into Tags values (485,"hacking");
insert into Tags values (486,"halloween");
insert into Tags values (487,"hallucinatory");
insert into Tags values (488,"handycam");
insert into Tags values (489,"hannibal lecter");
insert into Tags values (490,"happy ending");
insert into Tags values (491,"hard to watch");
insert into Tags values (492,"harry potter");
insert into Tags values (493,"harsh");
insert into Tags values (494,"haunted house");
insert into Tags values (495,"hawaii");
insert into Tags values (496,"heartbreaking");
insert into Tags values (497,"heartwarming");
insert into Tags values (498,"heist");
insert into Tags values (499,"heroin");
insert into Tags values (500,"heroine");
insert into Tags values (501,"heroine in tight suit");
insert into Tags values (502,"high fantasy");
insert into Tags values (503,"high school");
insert into Tags values (504,"highly quotable");
insert into Tags values (505,"hilarious");
insert into Tags values (506,"hillarious");
insert into Tags values (507,"hip hop");
insert into Tags values (508,"historical");
insert into Tags values (509,"history");
insert into Tags values (510,"hit men");
insert into Tags values (511,"hitchcock");
insert into Tags values (512,"hitman");
insert into Tags values (513,"holiday");
insert into Tags values (514,"hollywood");
insert into Tags values (515,"holocaust");
insert into Tags values (516,"homeless");
insert into Tags values (517,"homophobia");
insert into Tags values (518,"homosexuality");
insert into Tags values (519,"honest");
insert into Tags values (520,"hong kong");
insert into Tags values (521,"horrible");
insert into Tags values (522,"horror");
insert into Tags values (523,"horses");
insert into Tags values (524,"hospital");
insert into Tags values (525,"hostage");
insert into Tags values (526,"hotel");
insert into Tags values (527,"humanity");
insert into Tags values (528,"humor");
insert into Tags values (529,"humorous");
insert into Tags values (530,"hunting");
insert into Tags values (531,"idealism");
insert into Tags values (532,"identity");
insert into Tags values (533,"idiotic");
insert into Tags values (534,"imaginary friend");
insert into Tags values (535,"imagination");
insert into Tags values (536,"imdb top 250");
insert into Tags values (537,"immigrants");
insert into Tags values (538,"immortality");
insert into Tags values (539,"incest");
insert into Tags values (540,"independent film");
insert into Tags values (541,"india");
insert into Tags values (542,"indiana jones");
insert into Tags values (543,"indians");
insert into Tags values (544,"indie");
insert into Tags values (545,"infidelity");
insert into Tags values (546,"innocence lost");
insert into Tags values (547,"insanity");
insert into Tags values (548,"inspirational");
insert into Tags values (549,"inspiring");
insert into Tags values (550,"intellectual");
insert into Tags values (551,"intelligent");
insert into Tags values (552,"intelligent sci-fi");
insert into Tags values (553,"intense");
insert into Tags values (554,"interesting");
insert into Tags values (555,"internet");
insert into Tags values (556,"interracial romance");
insert into Tags values (557,"intimate");
insert into Tags values (558,"investigation");
insert into Tags values (559,"iran");
insert into Tags values (560,"iraq");
insert into Tags values (561,"iraq war");
insert into Tags values (562,"ireland");
insert into Tags values (563,"irish");
insert into Tags values (564,"irish accent");
insert into Tags values (565,"ironic");
insert into Tags values (566,"irreverent");
insert into Tags values (567,"islam");
insert into Tags values (568,"island");
insert into Tags values (569,"isolation");
insert into Tags values (570,"israel");
insert into Tags values (571,"italian");
insert into Tags values (572,"italy");
insert into Tags values (573,"james bond");
insert into Tags values (574,"jane austen");
insert into Tags values (575,"japan");
insert into Tags values (576,"japanese");
insert into Tags values (577,"jay and silent bob");
insert into Tags values (578,"jazz");
insert into Tags values (579,"jesus");
insert into Tags values (580,"jewish");
insert into Tags values (581,"jews");
insert into Tags values (582,"journalism");
insert into Tags values (583,"judaism");
insert into Tags values (584,"jungle");
insert into Tags values (585,"justice");
insert into Tags values (586,"kick-butt women");
insert into Tags values (587,"kidnapping");
insert into Tags values (588,"kids");
insert into Tags values (589,"kids and family");
insert into Tags values (590,"king arthur");
insert into Tags values (591,"kubrick");
insert into Tags values (592,"kung fu");
insert into Tags values (593,"kurosawa");
insert into Tags values (594,"lame");
insert into Tags values (595,"las vegas");
insert into Tags values (596,"latin america");
insert into Tags values (597,"lawyer");
insert into Tags values (598,"lawyers");
insert into Tags values (599,"lesbian");
insert into Tags values (600,"life");
insert into Tags values (601,"life & death");
insert into Tags values (602,"life philosophy");
insert into Tags values (603,"light");
insert into Tags values (604,"lions");
insert into Tags values (605,"literary adaptation");
insert into Tags values (606,"literature");
insert into Tags values (607,"liv tyler");
insert into Tags values (608,"london");
insert into Tags values (609,"lone hero");
insert into Tags values (610,"loneliness");
insert into Tags values (611,"long");
insert into Tags values (612,"los angeles");
insert into Tags values (613,"love");
insert into Tags values (614,"love story");
insert into Tags values (615,"love triangles");
insert into Tags values (616,"low budget");
insert into Tags values (617,"lynch");
insert into Tags values (618,"lyrical");
insert into Tags values (619,"macabre");
insert into Tags values (620,"mad scientist");
insert into Tags values (621,"made for tv");
insert into Tags values (622,"mafia");
insert into Tags values (623,"magic");
insert into Tags values (624,"magic realism");
insert into Tags values (625,"male nudity");
insert into Tags values (626,"man versus machine");
insert into Tags values (627,"manipulation");
insert into Tags values (628,"marijuana");
insert into Tags values (629,"marriage");
insert into Tags values (630,"mars");
insert into Tags values (631,"martial arts");
insert into Tags values (632,"marvel");
insert into Tags values (633,"marx brothers");
insert into Tags values (634,"masterpiece");
insert into Tags values (635,"math");
insert into Tags values (636,"mathematics");
insert into Tags values (637,"maze");
insert into Tags values (638,"medieval");
insert into Tags values (639,"meditative");
insert into Tags values (640,"melancholic");
insert into Tags values (641,"melancholy");
insert into Tags values (642,"memory");
insert into Tags values (643,"memory loss");
insert into Tags values (644,"mental hospital");
insert into Tags values (645,"mental illness");
insert into Tags values (646,"mentor");
insert into Tags values (647,"metaphysics");
insert into Tags values (648,"mexico");
insert into Tags values (649,"middle east");
insert into Tags values (650,"midlife crisis");
insert into Tags values (651,"military");
insert into Tags values (652,"mindfuck");
insert into Tags values (653,"mining");
insert into Tags values (654,"minnesota");
insert into Tags values (655,"mission from god");
insert into Tags values (656,"mistaken identity");
insert into Tags values (657,"miyazaki");
insert into Tags values (658,"mob");
insert into Tags values (659,"mockumentary");
insert into Tags values (660,"modern fantasy");
insert into Tags values (661,"money");
insert into Tags values (662,"monkey");
insert into Tags values (663,"monster");
insert into Tags values (664,"monsters");
insert into Tags values (665,"monty python");
insert into Tags values (666,"moody");
insert into Tags values (667,"moon");
insert into Tags values (668,"moral ambiguity");
insert into Tags values (669,"morality");
insert into Tags values (670,"mother daughter relationship");
insert into Tags values (671,"mother-son relationship");
insert into Tags values (672,"motorcycle");
insert into Tags values (673,"mountain climbing");
insert into Tags values (674,"movie business");
insert into Tags values (675,"movielens top pick");
insert into Tags values (676,"moving");
insert into Tags values (677,"mozart");
insert into Tags values (678,"mtv");
insert into Tags values (679,"multiple storylines");
insert into Tags values (680,"mummy");
insert into Tags values (681,"muppets");
insert into Tags values (682,"murder");
insert into Tags values (683,"murder mystery");
insert into Tags values (684,"music");
insert into Tags values (685,"music business");
insert into Tags values (686,"musical");
insert into Tags values (687,"musicians");
insert into Tags values (688,"mutants");
insert into Tags values (689,"mystery");
insert into Tags values (690,"mythology");
insert into Tags values (691,"narrated");
insert into Tags values (692,"nasa");
insert into Tags values (693,"native americans");
insert into Tags values (694,"natural disaster");
insert into Tags values (695,"nature");
insert into Tags values (696,"nazi");
insert into Tags values (697,"nazis");
insert into Tags values (698,"neil gaiman");
insert into Tags values (699,"neo-nazis");
insert into Tags values (700,"neo-noir");
insert into Tags values (701,"nerds");
insert into Tags values (702,"new jersey");
insert into Tags values (703,"new orleans");
insert into Tags values (704,"new york");
insert into Tags values (705,"new york city");
insert into Tags values (706,"new zealand");
insert into Tags values (707,"ninja");
insert into Tags values (708,"no dialogue");
insert into Tags values (709,"no plot");
insert into Tags values (710,"nocturnal");
insert into Tags values (711,"noir");
insert into Tags values (712,"noir thriller");
insert into Tags values (713,"non-hollywood ending");
insert into Tags values (714,"non-linear");
insert into Tags values (715,"nonlinear");
insert into Tags values (716,"nostalgia");
insert into Tags values (717,"nostalgic");
insert into Tags values (718,"not as good as the first");
insert into Tags values (719,"not funny");
insert into Tags values (720,"notable nudity");
insert into Tags values (721,"notable soundtrack");
insert into Tags values (722,"nuclear");
insert into Tags values (723,"nuclear bomb");
insert into Tags values (724,"nuclear war");
insert into Tags values (725,"nudity");
insert into Tags values (726,"nudity (full frontal - brief)");
insert into Tags values (727,"nudity (full frontal - notable)");
insert into Tags values (728,"nudity (full frontal)");
insert into Tags values (729,"nudity (rear)");
insert into Tags values (730,"nudity (topless - brief)");
insert into Tags values (731,"nudity (topless - notable)");
insert into Tags values (732,"nudity (topless)");
insert into Tags values (733,"obsession");
insert into Tags values (734,"ocean");
insert into Tags values (735,"off-beat comedy");
insert into Tags values (736,"office");
insert into Tags values (737,"oil");
insert into Tags values (738,"olympics");
insert into Tags values (739,"ominous");
insert into Tags values (740,"opera");
insert into Tags values (741,"organized crime");
insert into Tags values (742,"original");
insert into Tags values (743,"original plot");
insert into Tags values (744,"orphans");
insert into Tags values (745,"oscar");
insert into Tags values (746,"oscar (best actor)");
insert into Tags values (747,"oscar (best actress)");
insert into Tags values (748,"oscar (best animated feature)");
insert into Tags values (749,"oscar (best cinematography)");
insert into Tags values (750,"oscar (best directing)");
insert into Tags values (751,"oscar (best editing)");
insert into Tags values (752,"oscar (best effects - visual effects)");
insert into Tags values (753,"oscar (best foreign language film)");
insert into Tags values (754,"oscar (best music - original score)");
insert into Tags values (755,"oscar (best music - original song)");
insert into Tags values (756,"oscar (best picture)");
insert into Tags values (757,"oscar (best sound)");
insert into Tags values (758,"oscar (best supporting actor)");
insert into Tags values (759,"oscar (best supporting actress)");
insert into Tags values (760,"oscar (best writing - screenplay written directly for the screen)");
insert into Tags values (761,"oscar winner");
insert into Tags values (762,"over the top");
insert into Tags values (763,"overrated");
insert into Tags values (764,"palestine");
insert into Tags values (765,"parallel universe");
insert into Tags values (766,"paranoia");
insert into Tags values (767,"para0");
insert into Tags values (768,"parenthood");
insert into Tags values (769,"paris");
insert into Tags values (770,"parody");
insert into Tags values (771,"passionate");
insert into Tags values (772,"penguins");
insert into Tags values (773,"perfect");
insert into Tags values (774,"period piece");
insert into Tags values (775,"peter pan");
insert into Tags values (776,"pg");
insert into Tags values (777,"pg-13");
insert into Tags values (778,"philip k. dick");
insert into Tags values (779,"philosophical");
insert into Tags values (780,"philosophy");
insert into Tags values (781,"photographer");
insert into Tags values (782,"photography");
insert into Tags values (783,"pigs");
insert into Tags values (784,"pirates");
insert into Tags values (785,"pixar");
insert into Tags values (786,"pixar animation");
insert into Tags values (787,"plot");
insert into Tags values (788,"plot holes");
insert into Tags values (789,"plot twist");
insert into Tags values (790,"poetry");
insert into Tags values (791,"poignant");
insert into Tags values (792,"pointless");
insert into Tags values (793,"poker");
insert into Tags values (794,"poland");
insert into Tags values (795,"police");
insert into Tags values (796,"police corruption");
insert into Tags values (797,"police investigation");
insert into Tags values (798,"political");
insert into Tags values (799,"political corruption");
insert into Tags values (800,"politics");
insert into Tags values (801,"pornography");
insert into Tags values (802,"post apocalyptic");
insert into Tags values (803,"post-apocalyptic");
insert into Tags values (804,"potential oscar nom");
insert into Tags values (805,"poverty");
insert into Tags values (806,"powerful ending");
insert into Tags values (807,"predictable");
insert into Tags values (808,"pregnancy");
insert into Tags values (809,"prejudice");
insert into Tags values (810,"prequel");
insert into Tags values (811,"president");
insert into Tags values (812,"pretentious");
insert into Tags values (813,"prison");
insert into Tags values (814,"prison escape");
insert into Tags values (815,"private detective");
insert into Tags values (816,"product placement");
insert into Tags values (817,"prohibition");
insert into Tags values (818,"propaganda");
insert into Tags values (819,"prostitution");
insert into Tags values (820,"psychedelic");
insert into Tags values (821,"psychiatrist");
insert into Tags values (822,"psychiatry");
insert into Tags values (823,"psychological");
insert into Tags values (824,"psychology");
insert into Tags values (825,"pulp");
insert into Tags values (826,"punk");
insert into Tags values (827,"puppets");
insert into Tags values (828,"queer");
insert into Tags values (829,"quirky");
insert into Tags values (830,"quotable");
insert into Tags values (831,"rabbits");
insert into Tags values (832,"race");
insert into Tags values (833,"race issues");
insert into Tags values (834,"racing");
insert into Tags values (835,"racism");
insert into Tags values (836,"radio");
insert into Tags values (837,"rags to riches");
insert into Tags values (838,"rape");
insert into Tags values (839,"rats");
insert into Tags values (840,"realistic");
insert into Tags values (841,"realistic action");
insert into Tags values (842,"reality tv");
insert into Tags values (843,"rebellion");
insert into Tags values (844,"redemption");
insert into Tags values (845,"reflective");
insert into Tags values (846,"relationships");
insert into Tags values (847,"religion");
insert into Tags values (848,"remade");
insert into Tags values (849,"remake");
insert into Tags values (850,"revenge");
insert into Tags values (851,"revolution");
insert into Tags values (852,"ridiculous");
insert into Tags values (853,"rio de janeiro");
insert into Tags values (854,"road movie");
insert into Tags values (855,"road trip");
insert into Tags values (856,"roald dahl");
insert into Tags values (857,"robbery");
insert into Tags values (858,"robert downey jr");
insert into Tags values (859,"robert ludlum");
insert into Tags values (860,"robot");
insert into Tags values (861,"robots");
insert into Tags values (862,"rock and roll");
insert into Tags values (863,"romance");
insert into Tags values (864,"romantic");
insert into Tags values (865,"romantic comedy");
insert into Tags values (866,"rome");
insert into Tags values (867,"runaway");
insert into Tags values (868,"russia");
insert into Tags values (869,"russian");
insert into Tags values (870,"sacrifice");
insert into Tags values (871,"sad");
insert into Tags values (872,"sad but good");
insert into Tags values (873,"samurai");
insert into Tags values (874,"san francisco");
insert into Tags values (875,"sappy");
insert into Tags values (876,"sarcasm");
insert into Tags values (877,"satire");
insert into Tags values (878,"satirical");
insert into Tags values (879,"saturday night live");
insert into Tags values (880,"saturn award (best science fiction film)");
insert into Tags values (881,"saturn award (best special effects)");
insert into Tags values (882,"scary");
insert into Tags values (883,"scenic");
insert into Tags values (884,"schizophrenia");
insert into Tags values (885,"school");
insert into Tags values (886,"sci fi");
insert into Tags values (887,"sci-fi");
insert into Tags values (888,"science");
insert into Tags values (889,"science fiction");
insert into Tags values (890,"scifi");
insert into Tags values (891,"scifi cult");
insert into Tags values (892,"scotland");
insert into Tags values (893,"screwball");
insert into Tags values (894,"screwball comedy");
insert into Tags values (895,"script");
insert into Tags values (896,"secret service");
insert into Tags values (897,"secrets");
insert into Tags values (898,"segregation");
insert into Tags values (899,"self discovery");
insert into Tags values (900,"sentimental");
insert into Tags values (901,"sequel");
insert into Tags values (902,"sequels");
insert into Tags values (903,"serial killer");
insert into Tags values (904,"series");
insert into Tags values (905,"sex");
insert into Tags values (906,"sex comedy");
insert into Tags values (907,"sexual");
insert into Tags values (908,"sexual abuse");
insert into Tags values (909,"sexuality");
insert into Tags values (910,"sexualized violence");
insert into Tags values (911,"sexy");
insert into Tags values (912,"shakespeare");
insert into Tags values (913,"shallow");
insert into Tags values (914,"shark");
insert into Tags values (915,"shopping");
insert into Tags values (916,"short");
insert into Tags values (917,"short-term memory loss");
insert into Tags values (918,"silent");
insert into Tags values (919,"silly");
insert into Tags values (920,"silly fun");
insert into Tags values (921,"simple");
insert into Tags values (922,"single father");
insert into Tags values (923,"sisters");
insert into Tags values (924,"skinhead");
insert into Tags values (925,"slackers");
insert into Tags values (926,"slapstick");
insert into Tags values (927,"slasher");
insert into Tags values (928,"slavery");
insert into Tags values (929,"slow");
insert into Tags values (930,"slow paced");
insert into Tags values (931,"small town");
insert into Tags values (932,"snakes");
insert into Tags values (933,"so bad it's funny");
insert into Tags values (934,"so bad it's good");
insert into Tags values (935,"soccer");
insert into Tags values (936,"social commentary");
insert into Tags values (937,"solitude");
insert into Tags values (938,"sophia coppola");
insert into Tags values (939,"south africa");
insert into Tags values (940,"south america");
insert into Tags values (941,"southern theme");
insert into Tags values (942,"space");
insert into Tags values (943,"space opera");
insert into Tags values (944,"space program");
insert into Tags values (945,"space travel");
insert into Tags values (946,"spaghetti western");
insert into Tags values (947,"spain");
insert into Tags values (948,"spanish");
insert into Tags values (949,"spanish civil war");
insert into Tags values (950,"special");
insert into Tags values (951,"special effects");
insert into Tags values (952,"spelling bee");
insert into Tags values (953,"spiders");
insert into Tags values (954,"spielberg");
insert into Tags values (955,"spies");
insert into Tags values (956,"splatter");
insert into Tags values (957,"spock");
insert into Tags values (958,"spoof");
insert into Tags values (959,"sports");
insert into Tags values (960,"spy");
insert into Tags values (961,"spying");
insert into Tags values (962,"stage magic");
insert into Tags values (963,"stand-up comedy");
insert into Tags values (964,"star trek");
insert into Tags values (965,"star wars");
insert into Tags values (966,"steampunk");
insert into Tags values (967,"stereotypes");
insert into Tags values (968,"stoner movie");
insert into Tags values (969,"stop motion");
insert into Tags values (970,"stop-motion");
insert into Tags values (971,"story");
insert into Tags values (972,"storytelling");
insert into Tags values (973,"stranded");
insert into Tags values (974,"strange");
insert into Tags values (975,"strippers");
insert into Tags values (976,"studio ghibli");
insert into Tags values (977,"stunning");
insert into Tags values (978,"stupid");
insert into Tags values (979,"stupid as hell");
insert into Tags values (980,"stupidity");
insert into Tags values (981,"stylish");
insert into Tags values (982,"stylized");
insert into Tags values (983,"submarine");
insert into Tags values (984,"suburbia");
insert into Tags values (985,"suicide");
insert into Tags values (986,"suicide attempt");
insert into Tags values (987,"super hero");
insert into Tags values (988,"super-hero");
insert into Tags values (989,"superhero");
insert into Tags values (990,"superheroes");
insert into Tags values (991,"supernatural");
insert into Tags values (992,"suprisingly clever");
insert into Tags values (993,"surfing");
insert into Tags values (994,"surprise ending");
insert into Tags values (995,"surreal");
insert into Tags values (996,"surrealism");
insert into Tags values (997,"surveillance");
insert into Tags values (998,"survival");
insert into Tags values (999,"suspense");
insert into Tags values (1000,"suspenseful");
insert into Tags values (1001,"swashbuckler");
insert into Tags values (1002,"swedish");
insert into Tags values (1003,"sweet");
insert into Tags values (1004,"switching places");
insert into Tags values (1005,"sword fight");
insert into Tags values (1006,"sword fighting");
insert into Tags values (1007,"talking animals");
insert into Tags values (1008,"talky");
insert into Tags values (1009,"tarantino");
insert into Tags values (1010,"teacher");
insert into Tags values (1011,"tear jerker");
insert into Tags values (1012,"technology");
insert into Tags values (1013,"teen");
insert into Tags values (1014,"teen movie");
insert into Tags values (1015,"teenager");
insert into Tags values (1016,"teenagers");
insert into Tags values (1017,"teens");
insert into Tags values (1018,"teleportation");
insert into Tags values (1019,"television");
insert into Tags values (1020,"tense");
insert into Tags values (1021,"terminal illness");
insert into Tags values (1022,"terrorism");
insert into Tags values (1023,"texas");
insert into Tags values (1024,"thought-provoking");
insert into Tags values (1025,"thriller");
insert into Tags values (1026,"time");
insert into Tags values (1027,"time loop");
insert into Tags values (1028,"time travel");
insert into Tags values (1029,"tokyo");
insert into Tags values (1030,"tolkien");
insert into Tags values (1031,"tom clancy");
insert into Tags values (1032,"too long");
insert into Tags values (1033,"too short");
insert into Tags values (1034,"torture");
insert into Tags values (1035,"touching");
insert into Tags values (1036,"toys");
insert into Tags values (1037,"tragedy");
insert into Tags values (1038,"train");
insert into Tags values (1039,"trains");
insert into Tags values (1040,"transformation");
insert into Tags values (1041,"transgender");
insert into Tags values (1042,"travel");
insert into Tags values (1043,"treasure");
insert into Tags values (1044,"treasure hunt");
insert into Tags values (1045,"tricky");
insert into Tags values (1046,"trilogy");
insert into Tags values (1047,"true story");
insert into Tags values (1048,"truman capote");
insert into Tags values (1049,"twist");
insert into Tags values (1050,"twist ending");
insert into Tags values (1051,"twists & turns");
insert into Tags values (1052,"undercover cop");
insert into Tags values (1053,"underdog");
insert into Tags values (1054,"underrated");
insert into Tags values (1055,"understated");
insert into Tags values (1056,"underwater");
insert into Tags values (1057,"unfunny");
insert into Tags values (1058,"unintentionally funny");
insert into Tags values (1059,"unique");
insert into Tags values (1060,"united nations");
insert into Tags values (1061,"unlikeable characters");
insert into Tags values (1062,"unlikely friendships");
insert into Tags values (1063,"unrealistic");
insert into Tags values (1064,"unusual plot structure");
insert into Tags values (1065,"us history");
insert into Tags values (1066,"utopia");
insert into Tags values (1067,"vampire");
insert into Tags values (1068,"vampire human love");
insert into Tags values (1069,"vampires");
insert into Tags values (1070,"vengeance");
insert into Tags values (1071,"very funny");
insert into Tags values (1072,"very good");
insert into Tags values (1073,"very interesting");
insert into Tags values (1074,"video game");
insert into Tags values (1075,"video game adaptation");
insert into Tags values (1076,"video games");
insert into Tags values (1077,"videogame");
insert into Tags values (1078,"vienna");
insert into Tags values (1079,"vietnam");
insert into Tags values (1080,"vietnam war");
insert into Tags values (1081,"view askew");
insert into Tags values (1082,"vigilante");
insert into Tags values (1083,"vigilantism");
insert into Tags values (1084,"violence");
insert into Tags values (1085,"violent");
insert into Tags values (1086,"virginity");
insert into Tags values (1087,"virtual reality");
insert into Tags values (1088,"virus");
insert into Tags values (1089,"visceral");
insert into Tags values (1090,"visual");
insert into Tags values (1091,"visually appealing");
insert into Tags values (1092,"visually stunning");
insert into Tags values (1093,"visuals");
insert into Tags values (1094,"voodoo");
insert into Tags values (1095,"voyeurism");
insert into Tags values (1096,"war");
insert into Tags values (1097,"war movie");
insert into Tags values (1098,"wartime");
insert into Tags values (1099,"waste of time");
insert into Tags values (1100,"watch the credits");
insert into Tags values (1101,"weapons");
insert into Tags values (1102,"wedding");
insert into Tags values (1103,"weed");
insert into Tags values (1104,"weird");
insert into Tags values (1105,"werewolf");
insert into Tags values (1106,"werewolves");
insert into Tags values (1107,"western");
insert into Tags values (1108,"whimsical");
insert into Tags values (1109,"wilderness");
insert into Tags values (1110,"wine");
insert into Tags values (1111,"wistful");
insert into Tags values (1112,"witch");
insert into Tags values (1113,"witches");
insert into Tags values (1114,"witty");
insert into Tags values (1115,"wizards");
insert into Tags values (1116,"women");
insert into Tags values (1117,"working class");
insert into Tags values (1118,"workplace");
insert into Tags values (1119,"world politics");
insert into Tags values (1120,"world war i");
insert into Tags values (1121,"world war ii");
insert into Tags values (1122,"writer's life");
insert into Tags values (1123,"writers");
insert into Tags values (1124,"writing");
insert into Tags values (1125,"wuxia");
insert into Tags values (1126,"wwii");
insert into Tags values (1127,"zombie");
insert into Tags values (1128,"zombies");